services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
  ticklist-server:
    container_name: ticklist-server
    image: ticklist-server:latest
    build: ./ticklist-server
    ports:
      - "5000:5000"
    restart: always
  ticklist-app:
    container_name: ticklist-app
    image: ticklist-app:latest
    build: ./app
    ports:
      - "9000:9000"
    restart: always
